### PR TITLE
yt channel topics

### PR DESCRIPTION
**Pull request by kat-kel**
I added a functionality to the `youtube` commands that requests the Google-generated topics YouTube assigns to YouTube channels.

### CODE REVIEW

**Comment by boogheta** [comment]
This might be redundant with similar work that did @MiguelLaura on a separate branch to retrieve channels metadata. I'd go with first merging this one then refactor between the two works to merge all of it within a single youtube command, to be coordinated by @Yomguithereal after his return.

**Comment by kat-kel** [comment]
Thanks, Benjamin. I agree 100%. I'd already been calling the API for channel topics, which is data I want for the enrichment script I'm working on, and I already had some code written. I didn't realize Laura had made her pull request. 

YouTube channel topics are a different call than other channel metadata, and each call costs its own credits. But we could discuss whether we want to add another API call to the general metadata that Laura's pull request does. The channel topics request is not expensive. (Please correct me if I'm mistaken and don't hesitate to ask for clarity if what I've said isn't clear)

**Comment by kat-kel** [comment]
In an effort to be very clear:

The general metadata calls for a "snippet" and the channel topics calls for "topicDetails". They're separate calls to the API, but we could do both in one CLI command if we want.

**Comment by Yomguithereal** [comment]
@kat-kel they don't seem to be a different call to the API, we should be able to get everything in one call by specifying a full part parameter. On other routes some parts seems to cost more than others, but here the documentation does not state this, so I guess we can get everything at the same cost. @MiguelLaura will make some tests on #523

**Comment by kat-kel** [comment]
Great idea, Guillaume. I see in the doc that, "The part parameter specifies a comma-separated list of one or more search resource properties that the API response will include." So, if I understand, the idea is to concatenate the parts "snippet" and "topicDetails" in one call, i.e. "?part=snippet,topicDetails" Maybe also throw in "statistics" ?

**Comment by Yomguithereal** [comment]
@kat-kel #523 has been merged with various new parts added, as well as topics as you suggested. I think we got things in statistics, branding etc. It does not seem to cost more API quota but we shall test that further in the future (at least an increased quota cost is not documented).

**Pull request closed without merging**
